set -g @appearance_theme "dark"

set -g popup-border-style "bg=default fg=#54546d"
set -g pane-border-style "fg=#54546d"
set -g pane-active-border-style "bg=default fg=#7e9cd8"

set -g status-style "bg=#1f1f28 fg=#dcd7ba"
set -g status-left "#[bg=#7e9cd8,fg=#1f1f28,bold] #S #[bg=#1f1f28,fg=#7e9cd8,nobold]"
set -g status-right "#(~/.tmux/scripts/sync-appearance.sh)#[fg=#727169]%a #[fg=#938aa9]%Y-%m-%d #[fg=#dcd7ba,bold]%H:%M "

setw -g window-status-format "#[fg=#727169] #I:#W "
setw -g window-status-current-format "#[bg=#2a2a37,fg=#e6c384,bold] #I:#W "
setw -g window-status-style "bg=#1f1f28 fg=#727169"
setw -g window-status-current-style "bg=#2a2a37 fg=#e6c384"
setw -g window-status-activity-style "bg=#1f1f28 fg=#98bb6c,bold"
setw -g window-status-bell-style "bg=#1f1f28 fg=#e46876,bold"

set -g message-style "bg=#2a2a37 fg=#dcd7ba"
set -g message-command-style "bg=#2a2a37 fg=#7e9cd8"
set -g mode-style "bg=#7fb4ca fg=#1f1f28,bold"
set -g copy-mode-match-style "bg=#c4b28a fg=#1f1f28"
set -g copy-mode-current-match-style "bg=#e6c384 fg=#1f1f28,bold"
