set -g @appearance_theme "light"

set -g popup-border-style "bg=default fg=#9ca0b0"
set -g pane-border-style "fg=#bcc0cc"
set -g pane-active-border-style "bg=default fg=#1e66f5"

set -g status-style "bg=#eff1f5 fg=#4c4f69"
set -g status-left "#[bg=#1e66f5,fg=#eff1f5,bold] #S #[bg=#eff1f5,fg=#1e66f5,nobold]"
set -g status-right "#(~/.tmux/scripts/sync-appearance.sh)#[fg=#6c6f85]%a #[fg=#8839ef]%Y-%m-%d #[fg=#4c4f69,bold]%H:%M "

setw -g window-status-format "#[fg=#6c6f85] #I:#W "
setw -g window-status-current-format "#[bg=#ccd0da,fg=#df8e1d,bold] #I:#W "
setw -g window-status-style "bg=#eff1f5 fg=#6c6f85"
setw -g window-status-current-style "bg=#ccd0da fg=#df8e1d"
setw -g window-status-activity-style "bg=#eff1f5 fg=#40a02b,bold"
setw -g window-status-bell-style "bg=#eff1f5 fg=#d20f39,bold"

set -g message-style "bg=#ccd0da fg=#4c4f69"
set -g message-command-style "bg=#ccd0da fg=#1e66f5"
set -g mode-style "bg=#179299 fg=#eff1f5,bold"
set -g copy-mode-match-style "bg=#dc8a78 fg=#eff1f5"
set -g copy-mode-current-match-style "bg=#df8e1d fg=#eff1f5,bold"
